apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  storageClassName: manual
  capacity:
   storage: 500Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

